version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sistema-certificados-laravel-app
    container_name: sistema-certificados-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./sistema-metrologia-laravel:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:dummykey
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=metrologia
      - DB_USERNAME=metrologia
      - DB_PASSWORD=metrologia
    depends_on:
      - db
    ports:
      - "8000:8000"
  db:
    image: mysql:8.0
    container_name: sistema-certificados-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: metrologia
      MYSQL_USER: metrologia
      MYSQL_PASSWORD: metrologia
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  nginx:
    image: nginx:alpine
    container_name: sistema-certificados-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./sistema-metrologia-laravel:/var/www
      - ./sistema-metrologia-laravel/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
volumes:
  dbdata: 